language: cpp

# Specify an Ubuntu Trusty VM
sudo: required
dist: trusty

compiler:
    - gcc

addons:
    apt:
        # Use apt addon to facilitate multi-OS build later https://docs.travis-ci.com/user/multi-os/
        packages:
            - texlive-binaries # Temporary fix (?) for R bug http://bugs.debian.org/810963

before_install:
    # Use this to prepare the system to install prerequisites or dependencies

    # Confirm versions of key build tools
    - g++ --version
    - cmake --version

    # Add repository for R 
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
    - sudo add-apt-repository "deb http://cran.us.r-project.org/bin/linux/ubuntu trusty/"
    - sudo apt-get update -qq

install:
    # Use this to install any prerequisites or dependencies necessary to run your build

    # Install C++ build dependencies
    - sudo apt-get install libcurl4-openssl-dev --force-yes --assume-yes --fix-broken

    # Install Python build dependencies
    # `wheel` for packaging; `virtualenv` for testing
    - sudo apt-get install python python-dev python-pip --force-yes --assume-yes --fix-broken
    - pip install wheel virtualenv

    # Install R build dependencies
    # `Rcpp` for compilation; `roxygen2` for packaging; `svUnit`, `XML` & `libxml2-dev` for testing
    - sudo apt-get install r-base r-base-dev libxml2-dev --force-yes --assume-yes --fix-broken
    - sudo Rscript -e "install.packages(c('Rcpp','roxygen2','svUnit','XML'),lib='/usr/lib/R/library',repos='http://cran.us.r-project.org')"

before_script:
    # Use this to prepare your build for testing

    # Travis CI does a shallow clone of the current branch (`git clone --depth=50 --branch=develop ...`)
    # If the last tag was more than 50 commits in the past then the following `git describe` will fail and
    # the build will error. So, "unshallow" this clone to get a complete history
    - git fetch --unshallow

    # Display git tags in log
    - git describe --tags --dirty --long

script:
    - make vars
    - make cpp-tests-quick
    - make py-tests
    - make r-tests
