language: generic

branches:
    only:
        - master
        - develop

matrix:
  include:

    - os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      env:
        - DOCKER_BUILDS=true
        - PY_VERSION=2.7
        - R_VERSION=3.2

    - os: linux
      dist: trusty
      sudo: required
      env:
        #- PY_VERSION=3.4
        - R_VERSION=3.3

    #- os: osx

env:
    global:
        - secure: "jeBNOe2fnzzkwTJDTAtsVE1T6fzftCEAa72eALKE+9g2Bc+m0kSLW2Q3pyo4ozfPeTuk62MDD7aSbJLWfm6clnIw9uERxouENWpasRY+x+2UwhY5bT8FZU+lZ46FJg0PTW8Z1yCbs6gnet/U0rpLpAKb3eLuymlEJsyBK3VSPyQ=" # AWS_ACCESS_KEY_ID
        - secure: "ZMjOOsM7xc6QY0Xe3PVHxRtPvt6A8naD5k3O3EQtx8aNncLGDAgIhaJ1tKEPXRpFlMtY+5WNK1aMCFHRqCvxePHUxwZPtsBqHG+t9zua/bwjn7R5mnScqvFqVObdjJqMQDzGNN8Wfr+YJT5aibAuZamjioHUvhRmxYwG9lkzttM=" # AWS_SECRET_ACCESS_KEY
        - secure: "cU1i+QgY/GMs0h8id+Wdjv6VrgcEnaPfsaYYROLqM4VosenGiUn7DAFNESq+fowRvSqDtAE5HhCOsJ2MHcCCntfvPH7A5rajarlw5I+3RbU2y3LZIeWhV657r5G0nhmdHJ3U3vstPc1kREfVltDJF7YKA+QB6MM0moJ5ZwjjfTg=" # AWS_DEFAULT_REGION
        - secure: "IdWRjDeZgueABXWwR5dD/Y2UMDg5LbXOup09Yx7c72cxsYxtZli4LqSa+6oYooRYGh0IfHkGTx1VLYaohmFUMtKzAF6cjNoBY46g61QY3C5LSj3BmVvu9OVDq2+XMuZz39CDSUEg/miS9uD3W6NpMNtrVQAf/yzuCwo20Mg7h1Q=" # DOCKER_EMAIL
        - secure: "kciODef6f2M48C5+gHkFaaveMnenrPpE75yDW5of7L44E99zb5nVzvWedG8TXaqrLJlybv1pkKdUHYMUO3S+0oLw+ez4827sMO3NNz4odCR60mLVHAGkLTgPjv+OrF7G6aPDRy+d5jndBHhNrziPrSfuj9+F3dLLtCkva8Jhgis=" # DOCKER_USERNAME
        - secure: "p/eGwNKsY04as9DGyOZBFwMef6eKtw+mNC63TA/09CG4uS/oxQW2GjeHiqCKeP6UGjhEstV7op3m2Qep1WEDiWNbc8zfdSuYGkbxDnCaD0iyyDKOzrOOzR/yGXwOM6sCYnJ0RaBXfCXca+hPISc0ArK2Yhvp2xSfNUNEbbXIy4U=" # DOCKER_PASSWORD
        - secure: "F5BpK0/kVkgecKnYdGxCAd+qBCao/uYyVE48aPkyJQYTCvigRec/Fvc31FfQh/9W4ugXB1ZoTWQ+XSofJwHkkE9WOgqOHxMPb9VTIsBM7K6rrs1eG8jwenC0Acus0OVDqUORs62qPW4WHKA2haDJDQh6DbLcxEanNPolqVptJSg=" # STENCILA_TOKEN

addons:
    apt:
        # Install system level requirements for Linux
        packages:
            - libxml2-dev
            - libcurl4-openssl-dev
            - flex
            - lemon

before_install:
    # Use this to prepare the system to install prerequisites or dependencies

    # Use a python2.7 with UCS4 : https://github.com/travis-ci/travis-ci/issues/4948#issuecomment-165779970
    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

install:
    # Use this to install any prerequisites or dependencies necessary to run your build

    # Install system level requirements
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then ./setup/travis-osx-build.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./setup/travis-trusty-build.sh; fi

before_script:
    # Use this to prepare your build for testing

    # Confirm versions of key build tools and dependencies
    - openssl version
    - g++ --version
    - cmake --version
    - python --version
    - pip show pip setuptools wheel virtualenv
    - R --version
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker --version; fi

    # Travis CI does a shallow clone of the current branch (`git clone --depth=50 --branch=develop ...`)
    # If the last tag was more than 50 commits in the past then the following `git describe` will fail and
    # the build will error. So, "unshallow" this clone to get a complete history
    - git fetch --unshallow

    # Display git tags in log
    - git describe --tags --dirty --long

script:
    - make vars
    - make cpp-requires
    - make cpp-tests-quick -j2
    - make py-tests -j2
    - make r-tests -j2
    - |
        if [[ "$DOCKER_BUILDS" == "true" ]]; then
            docker pull stencila/ubuntu-14.04-py-2.7 && make docker-py-build
            docker pull stencila/ubuntu-14.04-r-3.2 && make docker-r-build
        fi

after_success:
    - bash <(curl -s https://codecov.io/bash)
    - | 
        if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
            make py-deliver
            make r-deliver
            if [[ "$DOCKER_BUILDS" == "true" ]]; then
                docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                make docker-py-deliver
                make docker-r-deliver
            fi
        fi

notifications:
    slack:
        secure: CZPtz/N4r7w0Xy5HLATXgL0mAcmLe2aiHpQGy7rOKw6Ahkqsr+XJNH4jrnHhaH3cYx4BQYjgSxtw2ha6vwdcTEK0qEj/I1Sr4hGrjGC296gByKpRxgUeUanJ5x6byfbWrJsJskvwRZAvso3CFRRNlUlfuwX8LpjT38ocK0HY+BQ=
    webhooks:
        urls:
            - secure: "c7sJb5i92rK48bkT/JEqjyrznBfLUAHcPr7vXTuFZGX5jn/g0tssCtsDiN08mvULuIJF2F2av/8SF9R2cSpeKkC69I9+YUn+uItq4zFISxzh7q3QfcWvQnbizCkjVDU+AxsTf4m9Kq3eatxwPNuAxRc6PGeaYQ5/NeMYFDkYGCk=" # Gitter
