language: node_js

node_js:
    - 6

cache:
  directories:
    - node_modules
    - build

before_script:
    # Using xvfb for headless browser based tests
    # Based on https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3

script:
    - make lint
    - make build
    - make cover

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:

    webhooks:
        urls:
            - secure: "c7sJb5i92rK48bkT/JEqjyrznBfLUAHcPr7vXTuFZGX5jn/g0tssCtsDiN08mvULuIJF2F2av/8SF9R2cSpeKkC69I9+YUn+uItq4zFISxzh7q3QfcWvQnbizCkjVDU+AxsTf4m9Kq3eatxwPNuAxRc6PGeaYQ5/NeMYFDkYGCk=" # Gitter
