language: node_js

node_js:
  - 6

cache:
  directories:
    - node_modules

script:
  - make lint
  - make test-documents
  - make cover
  - make docs

after_success:
  - bash <(curl -s https://codecov.io/bash)
