# Specify an Ubuntu Trusty VM
sudo: required
dist: trusty

language: cpp

compiler:
    - gcc

services:
    - docker

env:
    - secure: "p/eGwNKsY04as9DGyOZBFwMef6eKtw+mNC63TA/09CG4uS/oxQW2GjeHiqCKeP6UGjhEstV7op3m2Qep1WEDiWNbc8zfdSuYGkbxDnCaD0iyyDKOzrOOzR/yGXwOM6sCYnJ0RaBXfCXca+hPISc0ArK2Yhvp2xSfNUNEbbXIy4U="
    - secure: "RqUrcjfzMrv3TcqyplGDKPDLW3WZZ5VpqHHFZlOohBBhI2t3l1dSJX5MLvQOX/ynfF7SGklYXRpzOEyJ/B2UGF8SRNp0n7F15tgCpOJbwty5XULSDSynuSFvIXrumz/unJXXLANszWS5et/ABAFS5xnZV5E7uehFELtC+Enc6R8="
    - secure: "IdWRjDeZgueABXWwR5dD/Y2UMDg5LbXOup09Yx7c72cxsYxtZli4LqSa+6oYooRYGh0IfHkGTx1VLYaohmFUMtKzAF6cjNoBY46g61QY3C5LSj3BmVvu9OVDq2+XMuZz39CDSUEg/miS9uD3W6NpMNtrVQAf/yzuCwo20Mg7h1Q="
    - secure: "ZtjjaZJp5Vi2ao4c9Jvhe8qLtIav7RNtn7DNrqjQcOPwNkkRBYJwUG+TcRzmSHBZYS2cN7xih0z5dGOM8iZsa8MxK3X40GYnDwmP8u+bAFBJ7+wS6KFMQbWTqqLOCquyqDnGCNmEvIjRtpgNkOdP7kKjYjmB/OnZKx4taRUUNK0="

addons:
    apt:
        # Use apt addon to facilitate multi-OS build later https://docs.travis-ci.com/user/multi-os/
        packages:
            - texlive-binaries # Temporary fix (?) for R bug http://bugs.debian.org/810963

before_install:
    # Use this to prepare the system to install prerequisites or dependencies

    # Confirm versions of key build tools
    - g++ --version
    - cmake --version

    # Add repository for R 
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
    - sudo add-apt-repository "deb http://cran.us.r-project.org/bin/linux/ubuntu trusty/"
    - sudo apt-get update -qq

    # Login to Docker
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

install:
    # Use this to install any prerequisites or dependencies necessary to run your build

    # Install C++ build dependencies
    - sudo apt-get install libcurl4-openssl-dev --force-yes --assume-yes --fix-broken

    # Install Python build dependencies
    # `wheel` for packaging; `virtualenv` for testing
    - sudo apt-get install python python-dev --force-yes --assume-yes --fix-broken
    - curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | sudo python2.7
    - sudo -H pip install setuptools wheel virtualenv --upgrade
    - python2.7 --version
    - pip --version

    # Install R build dependencies
    # `Rcpp` for compilation; `roxygen2` for packaging; `svUnit`, `XML` & `libxml2-dev` for testing
    - sudo apt-get install r-base r-base-dev libxml2-dev --force-yes --assume-yes --fix-broken
    - sudo Rscript -e "install.packages(c('Rcpp','roxygen2','svUnit','XML'),lib='/usr/lib/R/library',repos='http://cran.us.r-project.org')"

before_script:
    # Use this to prepare your build for testing

    # Travis CI does a shallow clone of the current branch (`git clone --depth=50 --branch=develop ...`)
    # If the last tag was more than 50 commits in the past then the following `git describe` will fail and
    # the build will error. So, "unshallow" this clone to get a complete history
    - git fetch --unshallow

    # Display git tags in log
    - git describe --tags --dirty --long

script:
    - make vars
    - make cpp-tests-quick
    # Fails with "error: invalid command 'bdist_wheel'"
    # So temporarily skipping
    #- make py-tests
    - make r-tests
    - make docker-r-deliver

notifications:
  slack:
    secure: CZPtz/N4r7w0Xy5HLATXgL0mAcmLe2aiHpQGy7rOKw6Ahkqsr+XJNH4jrnHhaH3cYx4BQYjgSxtw2ha6vwdcTEK0qEj/I1Sr4hGrjGC296gByKpRxgUeUanJ5x6byfbWrJsJskvwRZAvso3CFRRNlUlfuwX8LpjT38ocK0HY+BQ=
