language: node_js

node_js:
  - 6

cache:
  directories:
    - node_modules

install:
  - git clone --depth=1 https://github.com/stencila/stencila ~/stencila
  - ln -sT ~/stencila/tests/documents $TRAVIS_BUILD_DIR/tests/documents

script:
  - make lint
  - make cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
