branches:
    only:
        - master
        - develop

# Specify an Ubuntu Trusty VM
sudo: required
dist: trusty

language: cpp

compiler:
    - gcc

services:
    - docker

env:
    global:
        - secure: "jeBNOe2fnzzkwTJDTAtsVE1T6fzftCEAa72eALKE+9g2Bc+m0kSLW2Q3pyo4ozfPeTuk62MDD7aSbJLWfm6clnIw9uERxouENWpasRY+x+2UwhY5bT8FZU+lZ46FJg0PTW8Z1yCbs6gnet/U0rpLpAKb3eLuymlEJsyBK3VSPyQ=" # AWS_ACCESS_KEY_ID
        - secure: "ZMjOOsM7xc6QY0Xe3PVHxRtPvt6A8naD5k3O3EQtx8aNncLGDAgIhaJ1tKEPXRpFlMtY+5WNK1aMCFHRqCvxePHUxwZPtsBqHG+t9zua/bwjn7R5mnScqvFqVObdjJqMQDzGNN8Wfr+YJT5aibAuZamjioHUvhRmxYwG9lkzttM=" # AWS_SECRET_ACCESS_KEY
        - secure: "cU1i+QgY/GMs0h8id+Wdjv6VrgcEnaPfsaYYROLqM4VosenGiUn7DAFNESq+fowRvSqDtAE5HhCOsJ2MHcCCntfvPH7A5rajarlw5I+3RbU2y3LZIeWhV657r5G0nhmdHJ3U3vstPc1kREfVltDJF7YKA+QB6MM0moJ5ZwjjfTg=" # AWS_DEFAULT_REGION
        - secure: "IdWRjDeZgueABXWwR5dD/Y2UMDg5LbXOup09Yx7c72cxsYxtZli4LqSa+6oYooRYGh0IfHkGTx1VLYaohmFUMtKzAF6cjNoBY46g61QY3C5LSj3BmVvu9OVDq2+XMuZz39CDSUEg/miS9uD3W6NpMNtrVQAf/yzuCwo20Mg7h1Q=" # DOCKER_EMAIL
        - secure: "kciODef6f2M48C5+gHkFaaveMnenrPpE75yDW5of7L44E99zb5nVzvWedG8TXaqrLJlybv1pkKdUHYMUO3S+0oLw+ez4827sMO3NNz4odCR60mLVHAGkLTgPjv+OrF7G6aPDRy+d5jndBHhNrziPrSfuj9+F3dLLtCkva8Jhgis=" # DOCKER_USERNAME
        - secure: "p/eGwNKsY04as9DGyOZBFwMef6eKtw+mNC63TA/09CG4uS/oxQW2GjeHiqCKeP6UGjhEstV7op3m2Qep1WEDiWNbc8zfdSuYGkbxDnCaD0iyyDKOzrOOzR/yGXwOM6sCYnJ0RaBXfCXca+hPISc0ArK2Yhvp2xSfNUNEbbXIy4U=" # DOCKER_PASSWORD
        - secure: "G59znslejKBG5Yf1JoYvaG2zLI7K/1cUOSP8KdTlmvr5o36yjCK2VZYP+ivpRRF9lAqh30xHOX7Idk+/WSv6bofR9IhBOBFa8eAhu83rAkV00f/aFd6R4+o7WCdrb1KXkyJWdghyk0IYrYHNPHRTAKRW1+rwgteozqCziuaBTLg=" # STENCILA_HUB_TOKEN

addons:
    apt:
        # Use apt addon to facilitate multi-OS build later https://docs.travis-ci.com/user/multi-os/
        packages:
            - texlive-binaries # Temporary fix (?) for R bug http://bugs.debian.org/810963
            - libxml2-dev
            - libcurl4-openssl-dev

before_install:
    # Use this to prepare the system to install prerequisites or dependencies

    # Add repository for R 
    # Using `source r-packages-trusty` in addons.apt instead of this 
    # gave an old version 3.0.2 (2013-09-25)
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
    - sudo add-apt-repository "deb http://cran.us.r-project.org/bin/linux/ubuntu trusty/"
    - sudo apt-get update -qq

install:
    # Use this to install any prerequisites or dependencies necessary to run your build

    # Install Python build dependencies (python and python-dev already installed)
    - pip2.7 install --upgrade --user travis pip setuptools wheel virtualenv

    # Install R build dependencies
    - sudo apt-get install r-base r-base-dev --force-yes --assume-yes --fix-broken
    - sudo Rscript -e "install.packages(c('Rcpp','roxygen2','svUnit','XML'),lib='/usr/lib/R/library',repos='http://cran.us.r-project.org')"

    # Install snippets build dependencies
    - pip2.7 install -r snippets/requirements.txt

    # Install build delivery dependencies
    - pip2.7 install --upgrade --user awscli

before_script:
    # Use this to prepare your build for testing

    # Confirm versions of key build tools
    - g++ --version
    - cmake --version
    - docker --version
    - python2.7 --version
    - pip2.7 show pip setuptools wheel virtualenv
    - R --version

    # Travis CI does a shallow clone of the current branch (`git clone --depth=50 --branch=develop ...`)
    # If the last tag was more than 50 commits in the past then the following `git describe` will fail and
    # the build will error. So, "unshallow" this clone to get a complete history
    - git fetch --unshallow

    # Display git tags in log
    - git describe --tags --dirty --long

script:
    - make vars
    - make cpp-tests-quick
    - make py-tests
    - make r-tests

after_success:
    - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - test $TRAVIS_PULL_REQUEST == "false" && make docker-r-deliver py-deliver r-deliver snippets-upload

notifications:
    slack:
        secure: CZPtz/N4r7w0Xy5HLATXgL0mAcmLe2aiHpQGy7rOKw6Ahkqsr+XJNH4jrnHhaH3cYx4BQYjgSxtw2ha6vwdcTEK0qEj/I1Sr4hGrjGC296gByKpRxgUeUanJ5x6byfbWrJsJskvwRZAvso3CFRRNlUlfuwX8LpjT38ocK0HY+BQ=
    webhooks:
        urls:
            - secure: "c7sJb5i92rK48bkT/JEqjyrznBfLUAHcPr7vXTuFZGX5jn/g0tssCtsDiN08mvULuIJF2F2av/8SF9R2cSpeKkC69I9+YUn+uItq4zFISxzh7q3QfcWvQnbizCkjVDU+AxsTf4m9Kq3eatxwPNuAxRc6PGeaYQ5/NeMYFDkYGCk=" # Gitter
