branches:
  only:
    - master
    - releases

version: '{build}'

environment:
  PATH: C:\msys64\usr\bin;C:\msys64\mingw32\bin;C:\Windows\System32;C:\Windows;%PATH%

install:
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER && ./setup/appveyor-build.sh"

build_script:
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER && make -C cpp requires library"
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER && make -C cpp tests-quick -j2"
