# Ansible playbook
# Sets up a machine to host user sessions

---

# Update system 

- hosts: all
  sudo: yes
  tasks:

    - name: ensure apt cache is up to date
      apt: update_cache=yes cache_valid_time=3600

    - name: ensure system is upgraded
      apt: upgrade=yes

# Setup Docker
# Based on:
#   https://docs.docker.com/installation/ubuntulinux/#ubuntu-trusty-1404-lts-64-bit

- hosts: all
  sudo: yes
  tasks:

    - name: ensure repositiories for docker are present
      apt_repository: repo="deb http://get.docker.io/ubuntu docker main" state=present

    - name: ensure key is docker apt key present
      apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9

    - name: ensure apt cache is up to date
      apt: update_cache=yes

    - name: ensure specific version of docker is installed
      apt: pkg=lxc-docker-1.5.0

    - name: docker command
      shell: ln -sf /usr/bin/docker.io /usr/local/bin/docker

    - name: docker autocompletion
      shell: sed -i '$acomplete -F _docker docker' /etc/bash_completion.d/docker.io
